sudo: false

language: node_js

env:
 - MONGO_URI_TEST=mongodb://localhost:27017/test

node_js:
  - "stable"

services:
  - mongodb

cache:
  npm: false

notifications:
  email: false

script:
  - cd server/
  - npm ci
  - npm test

after_success:
  - npm run coverage